= Sarah Taaher Bonna - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Invités

---
== Overview

|===
|_The purpose of this portfolio is to document my role and contributions to the project._
|===

*Invités* - An event management system. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

*Responsibility* - My task was to handle data filtration. I split this task into two. First, I created a Filter command
to handle data filtration for the payment status, attendance status and the tags, as these fields
are not unique to any person. Next, I modified the existing Find command to handle names,
phone numbers and email addresses, as these are fields used for identification, and the user may want to find a few
guests at one go. Rather than use the Filter command, which would yield results one-by-one,
the Find command allows you to find a few guests at the same time.

*Project Scope* - Invités is an application targeted at event managers and planners,
that allows you to better organise, cater, and manage the reception for large events
such as weddings, school gatherings, orientation camps, etc. Some of the main features
include the ability to send mass emails, keep track of payments, as well as the tab
keeping of attendance of the guests. To add to this, by employing a standardised format,
the application is able to take in Comma Separated Values (CSV) files and import data for
a particular event. This removes your need to input all the information manually,
as well as subsequently, gives you an alternative if you decide to organise another event
using the same guest list.

This will give you an easier time to manage the reception as you will be equipped with
tools that will minimise errors in catering, organising, and ordering. Moreover, this
application aims to reduce the frustrations for you when planning events and address your
needs in a platform that is more user-friendly, personalised, and efficient.

*Team:*

1. Aaryam - Mass Email Communication
2. Sandhya - Events Management
3. Sarah - Guest List Management
4. Tze Guang - Attendance Management
5. Wei Ming - Data Sharing

== Summary of contributions

|===
|_The purpose of this section is to list the contributions I have made to Invités._
|===

* *Major enhancement*: Added *the ability to filter data according to payment status, attendance
status and tags*
** What it does: allows the user to filter data based on keywords provided by you,
                 such as payment status, attendance status and/or tags, depending on the prefix used.
** Justification: This feature improves the product significantly because you can find guests who have yet to pay or are absent on the day of the event.
                  This will help you to be able to find people that fit the conditions you are looking for, without having to traverse the list manually.

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=sarahtaaherbonna[Sarah Taaher Bonna]]

* *Other contributions*:  +
1. Created Payment and Attendance attributes of a person.
Ensured that these attributes can only accept certain values.

2. Modified find command which allows the user to find guests with the name(s),
phone number(s) and/or email address(es), depending on the prefix used.
This modified feature improves the product because you can find a group of people, using their
name(s), phone number(s) and/or email address(es) at one go, instead of doing it one-by-one. As such,
you are able to find the necessary guests using any available contact details, not just the name.

** Enhancements to existing features:
*** Wrote additional tests for existing and new features to increase coverage (Pull requests [https://github.com/CS2113-AY1819S1-F09-3/main/pull/273[273]], [https://github.com/CS2113-AY1819S1-F09-3/main/pull/266[266]])
*** Did cosmetic tweaks to existing mark command to show updated list
(for example if filter a/absent, and then mark is performed, the person who has been
marked will no longer be in the list): [https://github.com/CS2113-AY1819S1-F09-3/main/pull/283[283]]
** Documentation:
*** Did cosmetic tweaks to existing contents of the Developer Guide
 and made important changes to the Use Cases: [https://github.com/CS2113-AY1819S1-F09-3/main/pull/144[144]]
*** Did cosmetic tweaks to existing contents of the User Guide: [https://github.com/CS2113-AY1819S1-F09-3/main/pull/218[218]], [https://github.com/CS2113-AY1819S1-F09-3/main/pull/266[266]], [https://github.com/CS2113-AY1819S1-F09-3/main/commit/09652199e0a7f2985c93fb907e345f357150449d[Commit 0965219]]
*** Added in the purpose of Invités in README.adoc: [https://github.com/CS2113-AY1819S1-F09-3/main/pull/2[2]]
** Community:
*** Reported bugs and suggestions for another team in the cohort (examples:  [https://github.com/CS2113-AY1819S1-T09-4/main/issues/137[137]], [https://github.com/CS2113-AY1819S1-T09-4/main/issues/144[144]])


== Contributions to the User Guide


|===
|_Given below are the sections that I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

=== *_Sections 3.3 and 3.15 of the User Guide_*

include::../UserGuide.adoc[tag=filter]

include::../UserGuide.adoc[tag=find]


== Contributions to the Developer Guide

|===
|_Given below are the sections that I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

=== *_Sections 4.1 and 4.2 of the Developer Guide_*

include::../DeveloperGuide.adoc[tag=filter]

include::../DeveloperGuide.adoc[tag=find]

=== *_Appendix F.2 and F.3 of the Developer Guide_*

include::../DeveloperGuide.adoc[tag=filterappendix]

include::../DeveloperGuide.adoc[tag=findappendix]



---
