= Sarah Taaher Bonna - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Invités

---
//Add in project scope
== Overview

The purpose of this portfolio is to document my role and contributions to the project.

Invités - An event management system. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

Responsibility - My task was to handle data filtration. I split this task into two. First, I created a Filter command
to handle data filtration for the payment status, attendance status and the tags, as these fields
were not unique to any person. Next, I modified the existing Find command to handle names,
phone numbers and email addresses, as these were unique fields, and the user may want to find a few
guests at one go. Rather than use the Filter command, which would yield results one-by-one,
the Find command allows the user to find a few guests at the same time.

Project Scope -

Team:

1. Aaryam - Mail feature
2. Sandhya - Events feature
3. Sarah - Data Filtration feature
4. Tze Guang - Attendance-taking feature
5. Wei Ming - Data Importation feature

== Summary of contributions

* *Major enhancement*: added *the ability to filter data*
** What it does: allows the user to filter data based on keywords provided by user,
                 such as payment status, attendance status and/or tags.
** Justification: This feature improves the product significantly because a user can find people who have yet to pay or are absent on the day of the event.
                  This will help users to be able to find people that fit the conditions they are looking for, without having to traverse the list manually.

* *Minor enhancement*: modified find command that allows the user to find guests with the name(s), phone number(s) and/or email address(es)
                       so that the user can find a group of people at one go, instead of doing it one-by-one.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_
//Done
* *Other contributions*: Created Payment and Attendance attributes of a person
//Need to change this
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from % to % (Pull requests https://github.com[#TBC], https://github.com[#TBC])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[TBC], https://github.com[TBC], https://github.com[TBC])

//Done
== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=filter]

include::../UserGuide.adoc[tag=find]

//Done
== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=filter]

include::../DeveloperGuide.adoc[tag=find]


== PROJECT: Invités

---
