= Sarah Taaher Bonna - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Invités

---
== Overview

|===
|_The purpose of this portfolio is to document my role and contributions to the project._
|===

Invités - An event management system. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

Responsibility - My task was to handle data filtration. I split this task into two. First, I created a Filter command
to handle data filtration for the payment status, attendance status and the tags, as these fields
are not unique to any person. Next, I modified the existing Find command to handle names,
phone numbers and email addresses, as these are unique fields, and the user may want to find a few
guests at one go. Rather than use the Filter command, which would yield results one-by-one,
the Find command allows the user to find a few guests at the same time.

Project Scope - Invités is an application targeted at event managers and planners,
that allows you to better organise, cater, and manage the reception for large events
such as weddings, school gatherings, orientation camps, etc. Some of the main features
include the ability to send mass emails, keep track of payments, as well as the tab
keeping of attendance of the guests. To add to this, by employing a standardised format,
the application is able to take in Comma Separated Values (CSV) files and import data for
a particular event. This removes your need having to input all the information manually,
as well as subsequently, gives you an alternative if you decide to organise another event
using the same guest list.

This will give you an easier time to manage the reception as you will be equipped with
tools that will minimise errors in catering, organisation, and orders. Moreover, this
application aims to reduce the frustrations for you when planning events and address your
needs in a platform that is more user friendly, personalised, and efficient.

Team:

1. Aaryam - Mail feature
2. Sandhya - Events feature
3. Sarah - Data Filtration feature
4. Tze Guang - Attendance-taking feature
5. Wei Ming - Data Importation feature

== Summary of contributions

|===
|_The purpose of this section is to list the contributions I have made to Invités._
|===

* *Major enhancement*: added *the ability to filter data according to payment status, attendance
status and tags*
** What it does: allows the user to filter data based on keywords provided by user,
                 such as payment status, attendance status and/or tags, depending on the prefix used.
** Justification: This feature improves the product significantly because a user can find people who have yet to pay or are absent on the day of the event.
                  This will help users to be able to find people that fit the conditions they are looking for, without having to traverse the list manually.

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=sarahtaaherbonna[Sarah Taaher Bonna]]

* *Other contributions*:  +
1. Created Payment and Attendance attributes of a person.
Ensured that these attributes can only accept certain values.

2. Modified find command which allows the user to find guests with the name(s),
phone number(s) and/or email address(es), depending on the prefix used.
This modified feature improves the product because a user can find a group of people, using their
name(s), phone number(s) and/or email address(es) at one go, instead of doing it one-by-one. As such,
the user is able to find the necessary guests using any available contact details, not just the name.

** Enhancements to existing features:
*** Wrote additional tests for existing and new features to increase coverage (Pull requests [https://github.com/CS2113-AY1819S1-F09-3/main/pull/273[273]], [https://github.com/CS2113-AY1819S1-F09-3/main/pull/266[266]])
** Documentation:
*** Did cosmetic tweaks to existing contents of the Developer Guide
 and made important changes to the Use Cases: [https://github.com/CS2113-AY1819S1-F09-3/main/pull/144[144]]
*** Did cosmetic tweaks to existing contents of the User Guide: [https://github.com/CS2113-AY1819S1-F09-3/main/pull/218[218]], [https://github.com/CS2113-AY1819S1-F09-3/main/pull/266[266]]
*** Added in the purpose of Invités in README.adoc: [https://github.com/CS2113-AY1819S1-F09-3/main/pull/2[2]]
** Community:
*** Reported bugs and suggestions for another team in the cohort (examples:  [https://github.com/CS2113-AY1819S1-T09-4/main/issues/137[137]], [https://github.com/CS2113-AY1819S1-T09-4/main/issues/144[144]])


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=filter]

include::../UserGuide.adoc[tag=find]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=filter]

include::../DeveloperGuide.adoc[tag=find]


== PROJECT: Invités

---
